version: '3.7'

services:
  postgres:
    image: postgres:10.1-alpine
    volumes:
      - './pdata:/var/lib/postgresql/data/'
    ports:
      - "5432:5432"

  hasker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/hasker'
    container_name: hasker
    working_dir: /hasker
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    tty: true
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  hasker-tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/hasker'
    container_name: hasker
    working_dir: /hasker
    command: pytest
    tty: true
    depends_on:
      - postgres